#### Stack operation
Stacking joins a sequence of tensors along a new axis

#### Concatenation operation
Concatenation joins a sequence of tensors along an existing axis.

##### Stacking in pytorch

In [3]:
import torch

In [11]:
t1= torch.tensor([1, 1, 1])  # there exist only row
t2 = torch.tensor([2, 2, 2])
t3 = torch.tensor([3, 3, 3])

In [5]:
t1.shape

torch.Size([3])

In [10]:
torch.cat((t1, t2, t3), dim=0) # dim=0 (is row) and dim=1 (is col)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [7]:
torch.cat((t1, t2, t3), dim=0).shape

torch.Size([9])

In [12]:
torch.stack((t1, t2, t3), dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [13]:
torch.stack((t1, t2, t3), dim=0).shape

torch.Size([3, 3])

In [14]:
torch.stack((t1, t2, t3), dim=1)  # along the column

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [16]:
T1 = torch.tensor([
    [1, 2, 3],
    [1, 2, 3]
])

In [17]:
T1.shape

torch.Size([2, 3])

In [18]:
T2 = torch.tensor([
    [1, 1, 1],
    [2, 2, 2]
])

In [19]:
torch.cat((T1, T2), dim=0)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 1, 1],
        [2, 2, 2]])

In [20]:
torch.cat((T1, T2), dim=0).shape

torch.Size([4, 3])

In [23]:
torch.cat((T1, T2), dim=1)

tensor([[1, 2, 3, 1, 1, 1],
        [1, 2, 3, 2, 2, 2]])

In [24]:
torch.stack((T1, T2), dim=0)

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 1, 1],
         [2, 2, 2]]])

In [26]:
torch.stack((T1, T2), dim=0).shape # add new axis to joins elements

torch.Size([2, 2, 3])

In [27]:
torch.stack((T1, T2), dim=1)

tensor([[[1, 2, 3],
         [1, 1, 1]],

        [[1, 2, 3],
         [2, 2, 2]]])

In [28]:
torch.stack((T1, T2), dim=1).shape # joining tensor along second axis

torch.Size([2, 2, 3])

In [30]:
torch.stack((T1, T2), dim=2).shape # joining tensor along third axis

torch.Size([2, 3, 2])