## PyTorch Tensor

In [1]:
import torch
import numpy as np

## Tensor class

In [2]:
t = torch.Tensor()

In [3]:
type(t)

torch.Tensor

## Tensor attributes

In [4]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [5]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1., 2., 3.])

In [6]:
t1.dtype

torch.int64

In [7]:
t2.dtype

torch.float32

In [8]:
t1 + t2

tensor([2., 4., 6.])

## creating tensor using numpy

In [9]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [12]:
torch.Tensor(data) # standard dtype=float32 => It is a contructor of a class.

tensor([1., 2., 3.])

In [13]:
torch.tensor(data) # no standard=> It is a factory function that returns an object.

tensor([1, 2, 3])

In [14]:
torch.as_tensor(data) # It is a factory function that returns an object.

tensor([1, 2, 3])

In [15]:
torch.from_numpy(data) # It is a factory function that returns an object.

tensor([1, 2, 3])

## creating tensor without numpy

In [16]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [17]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [18]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [19]:
torch.randn(2, 2)

tensor([[1.1857, 1.2783],
        [0.6078, 0.3738]])

### Creating pytorch tensor : Best Option

It is better to use factory function than using class constructor

In [20]:
torch.get_default_dtype()

torch.float32

In [22]:
torch.tensor(np.array([1, 2, 3])).dtype

torch.int64

In [26]:
t = torch.tensor(np.array([1, 2, 3]), dtype=torch.float64)

In [27]:
t

tensor([1., 2., 3.], dtype=torch.float64)

## Sharing memory for performance : copy vs share

In [31]:
#share data => doesnt make a copy of a data
#torch.as_tensor()
#orch.from_numpy()

In [32]:
# copy data => make a copy of a data
# torch.Tensor()
# torch.tensor()

## Best options

first

In [34]:
# torch.tensor() first best option

In [35]:
# torch.as_tensor() second best option for performance