## Tensor operation types

#### 1) Reshaping operation
#### 2) Element-wise operation
#### 3) Reduction operation
#### 4) Access operation


### 1) Reshaping operation

In [1]:
import torch

In [2]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
], dtype = torch.float32)

In [3]:
t.shape

torch.Size([3, 4])

In [4]:
t.size()

torch.Size([3, 4])

In [5]:
print(f'Rank of the tensor is {len(t.shape)}')

Rank of the tensor is 2


In [6]:
torch.tensor(t.shape).prod()

tensor(12)

In [7]:
t.numel() # number of elements in the tensor.

12

In [8]:
t.reshape(1, 12) # when we reshaping the tensor we must keep same rank of tensor.

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [9]:
t.reshape(2, 6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [10]:
t.reshape(4, 3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [11]:
t.reshape(6, 2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [12]:
t.reshape(12, 1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [13]:
## Squeezing the tensor => expanding and shrinking the rank of the tensor.

In [14]:
print(t.reshape(1, 12).squeeze().shape)

torch.Size([12])


In [15]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

In [16]:
t1.shape

torch.Size([2, 2])

In [17]:
t1.squeeze().shape

torch.Size([2, 2])

In [18]:
print(t.reshape(1, 12).shape)
print(t.reshape(1, 12).squeeze().shape) 
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0).shape)

torch.Size([1, 12])
torch.Size([12])
torch.Size([1, 12])


## Flatten operation
Flatten operation converts tensor of any shape into Rank1 tensor

In [19]:
def flatten(t):
    t = t.reshape(1, -1) # -1 represents any shape
    t = t.squeeze()
    return t

In [20]:
flatten(torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
]))

tensor([1, 2, 3, 4, 5, 6])

In [21]:
t3 = torch.ones(1, 2, 3)
t3

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [22]:
t3_flatten = flatten(t3)

In [23]:
t3_flatten.shape

torch.Size([6])

## CNN Flatten operation : Tensor batch processing

In [25]:
t1 = torch.tensor([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])

In [26]:
t2 = torch.tensor([
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2]
])

In [27]:
t3 = torch.tensor([
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3]
])

In [28]:
#these three tensor batch is represented by a single tensor

In [29]:
t = torch.stack((t1, t2, t3))
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [30]:
t.shape # here 3 represent batch size

torch.Size([3, 4, 4])

In [31]:
t = t.reshape(3, 1, 4, 4)

In [32]:
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [33]:
t.shape

torch.Size([3, 1, 4, 4])

In [34]:
t.flatten(start_dim=1).shape # only flattening the color channel axis

torch.Size([3, 16])