In [1]:
import torch
import numpy as np

In [2]:
# Converting a torch tensor to a numpy array

In [3]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [4]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [8]:
x = torch.rand((2,4))
x

tensor([[0.2836, 0.2084, 0.2487, 0.2064],
        [0.2901, 0.9058, 0.4720, 0.4081]])

In [9]:
y = x.numpy()
y

array([[0.28364253, 0.20840728, 0.24870503, 0.20644009],
       [0.29014957, 0.9057925 , 0.47200274, 0.40805268]], dtype=float32)

In [10]:
# converting a numpy array to torch tensor

In [11]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [12]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [13]:
# AUTOGRAD: AUTOMATIC DIFFERENTIATION

In [16]:
x = torch.ones((2, 2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [17]:
y = x + 3
print(y)

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)


In [18]:
# y was created as a result of an operation, so it has a grad_fn.

In [20]:
y.grad_fn

In [21]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[48., 48.],
        [48., 48.]], grad_fn=<MulBackward0>) tensor(48., grad_fn=<MeanBackward0>)


In [22]:
# Gradients

In [23]:
out.backward()

In [25]:
print(x.grad) # Print gradients d(out)/dx

tensor([[6., 6.],
        [6., 6.]])


In [30]:
y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([[512., 512.],
        [512., 512.]], grad_fn=<MulBackward0>)
