An element wise operation is an operation between two tensors that operates on corresponding elements within the respective tensors.

In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

In [3]:
t2 = torch.tensor([
    [9, 8],
    [7, 6]
], dtype=torch.float32)

In [4]:
# example from first axis

In [5]:
t1[0]

tensor([1., 2.])

In [6]:
t1[1]

tensor([3., 4.])

In [7]:
# example of second axis

In [8]:
t1[0][0]

tensor(1.)

In [9]:
# we know at same index element

In [10]:
t1[0][0]

tensor(1.)

In [11]:
t2[0][0]

tensor(9.)

to peform element wise operation two tensor must have the same number of elements.Also having same shape

In [12]:
t1 + t2 # element wise

tensor([[10., 10.],
        [10., 10.]])

In [13]:
t1 + 2 # here scalar value are rank 0 tensor
 # here scalar value 2 is broadcasted to  shape of t1

tensor([[3., 4.],
        [5., 6.]])

In [14]:
t1.add(2)


tensor([[3., 4.],
        [5., 6.]])

In [15]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)
t2 = torch.tensor([5, 6], dtype=torch.float32)

In [16]:
t1 + t2

tensor([[ 6.,  8.],
        [ 8., 10.]])

Comparision operation are element wise operation

In [17]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [18]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [19]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [20]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [28]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [21]:
a = torch.tensor([
    [2, 5]
])
b = torch.tensor([
    [2],
    [1]
])

In [22]:
a.shape

torch.Size([1, 2])

In [23]:
b.shape

torch.Size([2, 1])

In [24]:
a + b

tensor([[4, 7],
        [3, 6]])