 a reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor

## Argmax and reduction operations

In [2]:
import torch
import numpy as np

In [3]:
t = torch.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 0]
], dtype=torch.float32)

In [4]:
t.sum()

tensor(8.)

In [5]:
t.numel()

9

In [6]:
t.sum().numel()

1

In [7]:
t.sum().numel() < t.numel() # here reduction operation decreases the no of elements in the tensor.

True

### Some reduction operation

In [10]:
t.sum()

tensor(8.)

In [11]:
t.prod()

tensor(0.)

In [12]:
t.mean()

tensor(0.8889)

In [13]:
t.std()

tensor(1.1667)

### Reucing the tensor with respect to axis

In [14]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
], dtype=torch.float32)

In [15]:
t.shape

torch.Size([3, 4])

In [17]:
t.sum(dim=0) #  along first axis


tensor([6., 6., 6., 6.])

In [19]:
t[0]

tensor([1., 1., 1., 1.])

In [20]:
t[1]

tensor([2., 2., 2., 2.])

In [22]:
t[2]

tensor([3., 3., 3., 3.])

In [23]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

In [25]:
t.sum(dim=1) # along the second axis

tensor([ 4.,  8., 12.])

In [26]:
t[0].sum()

tensor(4.)

In [27]:
t[1].sum()

tensor(8.)

In [28]:
t[2].sum()

tensor(12.)

### Argmax tensor reduction operation
It tells index of maximum element in the specific tensor

In [29]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)

In [31]:
t.max()

tensor(5.)

In [32]:
t.argmax()

tensor(11)

In [33]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [34]:
t.mean()

tensor(1.5000)

In [35]:
t.mean().item()

1.5

In [36]:
t.mean(dim=0)

tensor([1.6667, 1.0000, 1.0000, 2.3333])

In [37]:
t.mean(dim=0).tolist()

[1.6666666269302368, 1.0, 1.0, 2.3333332538604736]