In [13]:
import torch

In [2]:
x = torch.Tensor([5, 3])
y = torch.Tensor([[2, 2]])

In [4]:
mul = x * y

In [5]:
print(mul)
print(mul.shape)

tensor([[10.,  6.]])
torch.Size([1, 2])


In [6]:
x = torch.zeros([2, 5])
y = torch.ones([2, 5])

In [7]:
sum = x + y

In [8]:
print(sum)
print(sum.shape)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.Size([2, 5])


In [10]:
y = torch.rand([3, 3])
print(y)

tensor([[0.8126, 0.1338, 0.5573],
        [0.4499, 0.4135, 0.3996],
        [0.2067, 0.2041, 0.5104]])


In [11]:
y.view([1, 9])

tensor([[0.8126, 0.1338, 0.5573, 0.4499, 0.4135, 0.3996, 0.2067, 0.2041, 0.5104]])